name: Local CI

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show project files
        run: |
          echo "Project files:"
          ls -la

      - name: Test Python syntax
        run: |
          python3 -m py_compile app.py

      - name: Build Docker image
        run: |
          docker build -t python-app:v1 .

      - name: Verify Docker image
        run: |
          docker images python-app